version: "2"
linters:
  default: all
  disable:
    # Inappropriate
    - depguard
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - lll
    - noinlineerr
    - paralleltest
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 20
    errcheck:
      exclude-functions:
        # Happens on exit via defer
        - (*go.uber.org/zap.Logger).Sync
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - github\.com\/leodido\/go-conventionalcommits
  exclusions:
    generated: strict
    presets:
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/maxbrunet/bitbucket-semantic-pull-requests)
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/maxbrunet/bitbucket-semantic-pull-requests
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
