version: "2"
linters:
  default: all
  disable:
    # Inappropriate
    - depguard
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - lll
    - paralleltest
    - varnamelen
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    errcheck:
      exclude-functions:
        # Happens on exit via defer
        - (*go.uber.org/zap.Logger).Sync
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - github\.com\/leodido\/go-conventionalcommits
  exclusions:
    rules:
      - linters:
          - errcheck
        # Taken from the default exclusions in v1
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/maxbrunet/bitbucket-semantic-pull-requests)
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/maxbrunet/bitbucket-semantic-pull-requests
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
