builds:
  - main: ./cmd/bitbucket-semantic-pull-requests
    ldflags:
      - '-X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - '7'
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{
      .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}'
    format: binary
checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'
kos:
  - repository: ghcr.io/maxbrunet/bitbucket-semantic-pull-requests
    bare: true
    tags:
      - '{{ .Tag }}'
      - latest
    base_image: cgr.dev/chainguard/static:latest@sha256:67a1b00e0134e2b3a614c7198a26f7deed9d11b7acad4d52c79c0cfd47a2eae7
    creation_time: '{{ .CommitTimestamp }}'
    ko_data_creation_time: '{{ .CommitTimestamp }}'
    labels:
      org.opencontainers.image.source: https://github.com/maxbrunet/bitbucket-semantic-pull-requests
      org.opencontainers.image.url: https://github.com/maxbrunet/bitbucket-semantic-pull-requests
      org.opencontainers.image.licenses: Apache-2.0
    platforms:
      - linux/386
      - linux/amd64
      - linux/arm/v7
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
